# -*- coding: utf-8 -*-
"""list ass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FvSWfuUimrMfCtELkG80wkv_xXP-hXrn

Access the 3rd element of a list.
"""

my_list = [10, 20, 30, 40, 50]
third_element = my_list[2]
print("The 3rd element is:", third_element)

"""Print the last element without using negative index.

"""

my_list = [10, 20, 30, 40, 50]
last_element = my_list[len(my_list)-1]
print("Last element:", last_element)

"""Slice a list to get first three items.

"""

my_list=[1, 2, 3, 4, 5]
first_three=my_list[:3]
print(first_three)

"""Slice to get every second element.

"""

my_list=[1, 2, 3, 4, 5]
every_second=my_list[::2]
print(every_second)

"""Reverse a list using slicing."""

my_list=[1, 2, 3, 4, 5]
reverse_list=my_list[::-1]
print(reverse_list)

"""Create a shallow copy of a list.

Find length of a list.
"""

my_list=[1, 2, 3, 4, 5]
list_length=(len(my_list))
print(list_length)

"""Find max value in a list."""

my_list=[10, 20, 30, 40, 50]
max_value=max(my_list)
print(max_value)

"""Find min value in a list.

"""

my_list=[10, 20, 30, 40, 50]
min_value=min(my_list)
print(min_value)

"""Remove the last element from a list.

"""

a=[10, 20, 30, 40, 50]
a.remove(50)
print(a)

"""Add an item to end of list."""

a=[10, 20, 30, 40, 50]
a.append(60)
print(a)

"""Insert element at index 1.

"""

a=[10, 20, 30, 40, 50]
a.insert(1,15)
print(a)

"""Convert string to list of characters.

"""

a=input("enter a string: ")
char_list=list(a)
print(char_list)

"""Convert string "a b c" to ['a','b','c']."""

a="abc"
char_list=list(a)
print(char_list)

"""Concatenate two lists.

"""

a=[1, 2, 3, 4, 5]
b=[6, 7, 8, 9, 10]
result=a+b
print(result)

"""Check if value exists in list.

"""

a=[1, 2, 3, 4, 5]
value=int(input("enter value to search: "))
if value in a:
  print("value exists in the list")
else:
  print("value not exist in the list")

"""Create a list from 1-5 using list constructor.

"""

a=list(range(1,6))
print(a)

"""Remove an item by value."""

a=[1, 2, 3, 4, 5]
a.remove(3)
print(a)

"""Clear all elements of a list.

"""

a=[1, 2, 3, 4, 5]
a.clear()
print(a)

"""Sort a list without modifying original list.

"""

a=[9, 3, 6, 2, 1]
a.sort()
print(a)