# -*- coding: utf-8 -*-
"""strings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xjUmG9I1OnG9W6ZBHG8tLkNYVr82B16P

swap two numbers without using third party
"""

a=int(input("enter a number"))
b=int(input("enter a number"))
a=a+b
b=a-b
a=a-b
swap=(a,b)
print(swap)

"""check weather number is even or odd

"""

n=int(input("enter a number"))
if n%2==0:
  print("even")
else:
  print("odd")

"""Take a string input and count how many vowels and consonants it has.

"""

a=str(input("enter a string"))
a=a.count(a)
a=a.count(e)
a=a.count(i)
a=a.count(o)
a=a.count(u)
print

"""Write a Python program to convert temperature from Celsius to Fahrenheit.

"""

celsius=float(input("enter the value"))
farenhiet=((celsius*9/5)+32)
print("{farenheit}")

"""Write a program to check if a given string is a palindrome or not.

"""

text = input("Enter a string: ")
# Remove spaces and convert to lowercase for uniform comparison
cleaned_text = text.replace(" ", "").lower()
# Check palindrome
if cleaned_text == cleaned_text[::-1]:
    print(f"'{text}' is a palindrome.")
else:
    print(f"'{text}' is not a palindrome.")

"""Write a program to take two numbers and display the larger one."""

n1=int(input("enter a number"))
n2=int(input("enter a number"))
if n1>n2:
  print(n1)
else:
  print(n2)

"""Create a program to reverse a given string using slicing.

"""

s=input("enter a text")
print(s[::-1])

"""Write a Python script to find ASCII value of a character.

"""

char = input("Enter a character: ")
if len(char) == 1:
    print( ord(char))
else:
    print("Please enter exactly one character.")

"""Write a program that reads a number and prints its multiplication table.

"""

n=int(input("enter a number"))
print(f"multiplication table of {n}")
for i in range(1,11):
    print(f"{n}*{i}={n*i}")

"""Write a Python program to check whether a character is alphabet, digit, or special character.

"""

char=input("enter a character: ")
if len(char)!=1:
  print("please enter exactly one character")
else:
 if char.isalpha():
  print(char,"is an alphabet")
 elif char.isdigit():
  print(char,"is an digit")
 else:
  print(char,"is an special character")

"""Write a program to count the number of words in a string.

"""

text = input("Enter a sentence: ")
# Split the string into words
words = text.split()

# Count the words
count = len(words)

print("Number of words:", count)

"""given input a='data science' and expected output is data scjience"""

a='data science'
a=a.replace('i','ji')
print(a)

"""Write a Python program to find the maximum and minimum of three numbers using conditional statements.

"""

a=int(input("Enter a number: "))