# -*- coding: utf-8 -*-
"""tuples ass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17980jCTV_EeRmVxIDyLAJHAvGsX2r05t

Create an empty tuple.
"""

a=(1, 2, 3, 4, 5)
empty_tuple=()
print(empty_tuple)

"""Create a tuple with 5 integers."""

a=(1, 2, 3, 4, 5)
print(a)

"""Access 3rd element of a tuple.

"""

a=(1, 2, 3, 4, 5)
third_element=a[2]
print(third_element)

"""Access last element without negative index."""

a=(1, 2, 3, 4, 5)
last_element=a[4]
print(last_element)

"""Slice first three elements.

"""

a=(1, 2, 3, 4, 5)
print(a[:-3])

"""Slice every alternate value.

"""

a=(1, 2, 3, 4, 5)
print(a[::2])

"""Reverse a tuple using slicing.

"""

a=(1, 2, 3, 4, 5)
print(a[::-1])

"""Concatenate two tuples.

"""

a=(1, 2, 3, 4, 5)
b=(6, 7, 8, 9, 10)
result=a+b
print(result)

"""Replicate tuple (1,2) twice.

"""

a=(1,2)
b=(1,2)*2
print(b)

"""Find length of a tuple.

"""

a=(1, 2, 3, 4, 5)
print(len(a))

"""Convert a list to a tuple.

"""

a=[1, 2, 3, 4, 5]
b=tuple(a)
print(b)

"""Convert a string "python" to tuple of characters."""

a="python"
chr_tuple=tuple(a)
print(chr_tuple)

"""Check if value exists in tuple.

"""

a=[1, 2, 3, 4, 5]
value=int(input("Enter value to search: "))
if value in a:
  print("value exists in a")
else:
  print("value not exists in a")

"""Find maximum element in tuple.

"""

a=[1, 2, 3, 4, 5]
print(max(a))

"""Find minimum element in tuple.

"""

a=[1, 2, 3, 4, 5]
print(min(a))

"""Count how many times 2 appears in (1,2,2,3).

"""

a=(1, 2, 2, 3)
a=a.count(2)
print(a)

"""Find index of an element.

"""

a=(1, 2, 2, 3)
a=a.index(1)
print(a)

"""Perform tuple packing.

"""

a=1,2,3
print(a)

"""Perform tuple unpacking into variables.

"""

a,b,c=1,2,3
print(a)
print(b)
print(c)

"""Convert tuple to string without loops.

"""

a=(1, 2, 3, 4, 5)
b=" ".join(a)
print(b)